### ISSUE TITLE
Cannot create new game

### ISSUE THREAD

**Issue by AutoJill** [seanlerner/tovgdb#2]
From Slack: "Okay so I've attempted to create a listing for The Yawhg, filled in all applicable fields and hit create. I get an error "Warning! Could not save Game. Please correct and try again." but scrolling through the form, there does not appear to be anything I have missed out on and no prompt explaining the issue can be found."

Sagan: I get the same issue so it's not an admin problem; all my required fields have been filled out so not sure what the error is.

![screen shot 2016-08-07 at 1 16 41 pm](https://cloud.githubusercontent.com/assets/10978724/17463987/d7915fe2-5ca1-11e6-83c1-c5af048b3500.png)

**Comment by AutoJill** [comment]
I just created a TEST GAME entry with only the bare minimum fields filled out (Name and Local/Online) and that seemed to work??

http://tovgdb.smallcity.ca/admin/games/155

**Comment by AutoJill** [comment]
Figured out that you can work around it by creating a game with only the asterisked fields filled in (Name and Local/Online), then going back and editing in the rest of the info.

My test game here:
http://tovgdb.smallcity.ca/admin/games/155

**Comment by seanlerner** [comment]
I found a work around for this, but I may have introduced some new issues. I'll take another look at this tomorrow.

**Comment by seanlerner** [comment]
I've fixed this.
