### ISSUE TITLE
Publication Status not showing correctly on show or edit of game

### ISSUE THREAD

**Issue by AutoJill** [seanlerner/tovgdb#3]
Tried to change the Publication Status of the LIADST entry but when I hit Save, it just reverts back to Ready for Processing. This happens with a few other entries.

http://tovgdb.smallcity.ca/admin/games/80

**Comment by AutoJill** [comment]
I think it's sort of working? But when I click save, it still tells me it's marked "Ready for processing" even though it shows up in the Admin in the right section

**Comment by seanlerner** [comment]
I've fixed this.
