### ISSUE TITLE
Need to be able to mass change publication statuses for multiple entries at a time?

### ISSUE THREAD

**Issue by AutoJill** [seanlerner/tovgdb#5]
Is this already possible? I didn't see a way to do it

**Comment by seanlerner** [comment]
@AutoJill Hi Sagan, for this, is this a one time need thing or an on-going feature? it might be much easier for me to just write a little script to do this then create a feature for this.

**Comment by AutoJill** [comment]
Yeah I think one-time thing for now, I just want to be able to publish all entries at the same time when the site goes live

**Comment by seanlerner** [comment]
Okay, I'll close this for now then, and when you'd like me to switch all the entries to published, just open a new ticket (or re-open this ticket) and I'll go ahead and do that.
